/** Initial content when JSON store is empty (matches current site). */
export const defaultMenu = {
  items: [
    {
      id: 'antipasto-misto',
      order: 0,
      name: { nl: 'Antipasto misto', en: 'Antipasto misto', it: 'Antipasto misto' },
      course: { nl: 'Antipasti', en: 'Antipasti', it: 'Antipasti' },
      imageUrl: null,
    },
    {
      id: 'bruschetta',
      order: 1,
      name: { nl: 'Bruschetta al pomodoro', en: 'Bruschetta al pomodoro', it: 'Bruschetta al pomodoro' },
      course: { nl: 'Antipasti', en: 'Antipasti', it: 'Antipasti' },
      imageUrl: null,
    },
    {
      id: 'carpaccio',
      order: 2,
      name: { nl: 'Carpaccio di manzo', en: 'Carpaccio di manzo', it: 'Carpaccio di manzo' },
      course: { nl: 'Antipasti', en: 'Antipasti', it: 'Antipasti' },
      imageUrl: null,
    },
    {
      id: 'tagliatelle',
      order: 3,
      name: { nl: 'Spaghetti al ragù', en: 'Spaghetti al ragù', it: 'Spaghetti al ragù' },
      course: { nl: 'Pasta & risotto', en: 'Pasta & risotto', it: 'Pasta & risotto' },
      imageUrl: null,
    },
    {
      id: 'risotto',
      order: 4,
      name: { nl: 'Risotto ai funghi', en: 'Risotto ai funghi', it: 'Risotto ai funghi' },
      course: { nl: 'Pasta & risotto', en: 'Pasta & risotto', it: 'Pasta & risotto' },
      imageUrl: null,
    },
    {
      id: 'vongole',
      order: 5,
      name: { nl: 'Spaghetti alle vongole', en: 'Spaghetti alle vongole', it: 'Spaghetti alle vongole' },
      course: { nl: 'Pasta & risotto', en: 'Pasta & risotto', it: 'Pasta & risotto' },
      imageUrl: null,
    },
    {
      id: 'saltimbocca',
      order: 6,
      name: { nl: 'Scaloppine ai funghi', en: 'Scaloppine ai funghi', it: 'Scaloppine ai funghi' },
      course: { nl: 'Secondi', en: 'Mains', it: 'Secondi' },
      imageUrl: null,
    },
    {
      id: 'branzino',
      order: 7,
      name: { nl: 'Branzino al forno', en: 'Branzino al forno', it: 'Branzino al forno' },
      course: { nl: 'Secondi', en: 'Mains', it: 'Secondi' },
      imageUrl: null,
    },
    {
      id: 'scaloppine',
      order: 8,
      name: { nl: 'Pollo al limone', en: 'Pollo al limone', it: 'Pollo al limone' },
      course: { nl: 'Secondi', en: 'Mains', it: 'Secondi' },
      imageUrl: null,
    },
    {
      id: 'tiramisu',
      order: 9,
      name: { nl: 'Tiramisù della casa', en: 'Tiramisù della casa', it: 'Tiramisù della casa' },
      course: { nl: 'Dolci', en: 'Desserts', it: 'Dolci' },
      imageUrl: null,
    },
    {
      id: 'panna-cotta',
      order: 10,
      name: { nl: 'Panna cotta', en: 'Panna cotta', it: 'Panna cotta' },
      course: { nl: 'Dolci', en: 'Desserts', it: 'Dolci' },
      imageUrl: null,
    },
    {
      id: 'cannoli',
      order: 11,
      name: { nl: 'Cannoli siciliani', en: 'Cannoli siciliani', it: 'Cannoli siciliani' },
      course: { nl: 'Dolci', en: 'Desserts', it: 'Dolci' },
      imageUrl: null,
    },
  ],
};

export const defaultGallery = { items: [] };

export const defaultEvents = {
  items: [
    {
      id: 'tango',
      order: 0,
      sede: 'leiden',
      legacyKey: 'tango',
      flyerUrl: null,
      title: { nl: 'Il Salotto del Tango', en: 'Il Salotto del Tango', it: 'Il Salotto del Tango' },
      kicker: { nl: 'Speciale avond · Leiden', en: 'Special evening · Leiden', it: 'Serata speciale · Leiden' },
      dateLine: { nl: 'Zaterdag 23 augustus 2026', en: 'Saturday 23 August 2026', it: 'Sabato 23 agosto 2026' },
      slogan: { nl: 'Tango, wijn & Italiaanse warmte', en: 'Tango, wine & Italian warmth', it: 'Tango, vino e calore italiano' },
      lead: { nl: 'Een avond vol passie en elegantie.', en: 'An evening of passion and elegance.', it: 'Una serata di passione ed eleganza.' },
      body: {
        nl: 'Il Salotto del Tango — intieme samenkomst met muziek en goed gezelschap.',
        en: 'Il Salotto del Tango — an intimate gathering with music and good company.',
        it: 'Il Salotto del Tango — incontro intimo con musica e buona compagnia.',
      },
      when: { nl: '23 aug 2026 · 19:00', en: '23 Aug 2026 · 7:00 PM', it: '23 ago 2026 · 19:00' },
      where: {
        nl: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        en: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        it: 'Bacco Perbacco · Morstraat 6-8, Leiden',
      },
      price: { nl: 'Op aanvraag', en: 'On request', it: 'Su richiesta' },
      tags: { nl: 'Tango · Live · Leiden', en: 'Tango · Live · Leiden', it: 'Tango · Live · Leiden' },
    },
    {
      id: 'sarda',
      order: 1,
      sede: 'leiden',
      legacyKey: 'sarda',
      flyerUrl: null,
      title: { nl: 'Serata Sarda', en: 'Serata Sarda', it: 'Serata Sarda' },
      kicker: { nl: 'Sardinische avond · Leiden', en: 'Sardinian evening · Leiden', it: 'Serata sarda · Leiden' },
      dateLine: { nl: 'Vrijdag 10 oktober 2026', en: 'Friday 10 October 2026', it: 'Venerdì 10 ottobre 2026' },
      slogan: { nl: 'Sapori e tradizioni van Sardinië', en: 'Flavours and traditions of Sardinia', it: 'Sapori e tradizioni della Sardegna' },
      lead: { nl: 'Een feest van authenticiteit.', en: 'A celebration of authenticity.', it: 'Una festa di autenticità.' },
      body: {
        nl: 'Serata Sarda met muziek, gerechten en gastvrijheid.',
        en: 'Serata Sarda with music, food and hospitality.',
        it: 'Serata Sarda con musica, piatti e ospitalità.',
      },
      when: { nl: '10 okt 2026 · 19:00', en: '10 Oct 2026 · 7:00 PM', it: '10 ott 2026 · 19:00' },
      where: {
        nl: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        en: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        it: 'Bacco Perbacco · Morstraat 6-8, Leiden',
      },
      price: { nl: 'Op aanvraag', en: 'On request', it: 'Su richiesta' },
      tags: { nl: 'Sardegna · Musica · Leiden', en: 'Sardinia · Music · Leiden', it: 'Sardegna · Musica · Leiden' },
    },
    {
      id: 'stellato',
      order: 2,
      sede: 'leiden',
      legacyKey: 'stellato',
      flyerUrl: null,
      title: { nl: 'Menu Stellato a 6 Mani', en: 'Menu Stellato a 6 Mani', it: 'Menu Stellato a 6 Mani' },
      kicker: { nl: 'Chef avond · Leiden', en: 'Chef evening · Leiden', it: 'Serata chef · Leiden' },
      dateLine: { nl: '30–31 oktober 2026', en: '30–31 October 2026', it: '30–31 ottobre 2026' },
      slogan: { nl: 'Fine dining met drie sterrenchefs', en: 'Fine dining with three star chefs', it: 'Fine dining con tre chef stellati' },
      lead: { nl: 'Een unieke gastronomische ervaring.', en: 'A unique gastronomic experience.', it: 'Un\'esperienza gastronomica unica.' },
      body: {
        nl: 'Basile, Laudani en Alioto — twee avonden Menu Stellato.',
        en: 'Basile, Laudani and Alioto — two evenings of Menu Stellato.',
        it: 'Basile, Laudani e Alioto — due serate Menu Stellato.',
      },
      when: { nl: '30–31 okt 2026', en: '30–31 Oct 2026', it: '30–31 ott 2026' },
      where: {
        nl: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        en: 'Bacco Perbacco · Morstraat 6-8, Leiden',
        it: 'Bacco Perbacco · Morstraat 6-8, Leiden',
      },
      price: { nl: 'Op aanvraag', en: 'On request', it: 'Su richiesta' },
      tags: { nl: 'Chef · Stellato · Leiden', en: 'Chef · Stellato · Leiden', it: 'Chef · Stellato · Leiden' },
    },
  ],
};
