/** Seed guest feedback when storage is empty (local + Railway first boot). */
export const defaultFeedback = {
  items: [
    {
      id: 'fb-seed-nl-01',
      name: 'Sophie van der Berg',
      location: 'den-haag',
      rating: 5,
      message:
        'Wat een heerlijke avond! De tagliatelle al ragù smaakte precies zoals in Toscane. Roberta en Giuseppe maken je echt welkom — absolute aanrader in Den Haag.',
      language: 'nl',
      createdAt: '2025-11-14T19:42:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-02',
      name: 'Mark de Vries',
      location: 'leiden',
      rating: 5,
      message:
        'Intieme sfeer in Leiden, perfect voor een verjaardagsdiner. De tiramisù was hemels. Dit is voor ons het beste Italiaanse restaurant in de regio.',
      language: 'nl',
      createdAt: '2025-12-03T20:15:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-03',
      name: 'Elena Bakker',
      location: 'den-haag',
      rating: 5,
      message:
        'Zaterdaglunch met het gezin — kindvriendelijk én authentiek. Bruschetta en risotto waren top. Warme familiesfeer, precies wat je zoekt bij een trattoria.',
      language: 'nl',
      createdAt: '2026-01-18T12:30:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-04',
      name: 'Thomas Jansen',
      location: 'leiden',
      rating: 5,
      message:
        'Na een dag in het centrum van Leiden hier gegeten: vongole, perfecte wijnkeuze, service met een glimlach. Vijf sterren zonder twijfel.',
      language: 'nl',
      createdAt: '2026-02-07T18:55:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-05',
      name: 'Fatima El Amrani',
      location: 'den-haag',
      rating: 5,
      message:
        'Eindelijk een Italiaan in Den Haag waar alles klopt: pasta al dente, niet te zout, echte olijfolie. Giuseppe kwam even langs aan tafel — hartverwarmend.',
      language: 'nl',
      createdAt: '2026-03-22T17:20:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-06',
      name: 'Pieter Kuipers',
      location: 'leiden',
      rating: 5,
      message:
        'Romantisch diner met mijn partner. Scaloppine ai funghi en een huiswijn die perfect paste. Bacco Perbacco voelt als Italië in Nederland.',
      language: 'nl',
      createdAt: '2026-04-11T20:40:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-nl-07',
      name: 'Anouk Vermeer',
      location: 'den-haag',
      rating: 5,
      message:
        'We komen nu elke maand terug. Consistente kwaliteit, vriendelijk team, en gerechten met ziel. Beste pasta in Den Haag, punt uit.',
      language: 'nl',
      createdAt: '2026-06-28T21:05:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-01',
      name: 'James Mitchell',
      location: 'den-haag',
      rating: 5,
      message:
        'Outstanding Italian food in The Hague. The carpaccio was delicate, the saltimbocca full of flavour. Roberta and Giuseppe make you feel like family.',
      language: 'en',
      createdAt: '2025-10-09T19:10:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-02',
      name: 'Sarah Chen',
      location: 'leiden',
      rating: 5,
      message:
        'We booked Leiden for a special evening and it exceeded expectations. Cozy atmosphere, authentic recipes, and the panna cotta was the perfect finish.',
      language: 'en',
      createdAt: '2025-11-28T20:25:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-03',
      name: 'David O\'Connor',
      location: 'den-haag',
      rating: 5,
      message:
        'Weekend lunch in Den Haag — generous portions, real Italian hospitality. Best trattoria we have found since moving to the Netherlands.',
      language: 'en',
      createdAt: '2026-01-05T13:00:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-04',
      name: 'Emily Watson',
      location: 'leiden',
      rating: 5,
      message:
        'Hidden gem in Leiden. The risotto was creamy without being heavy, and the staff remembered it was our anniversary. Truly five stars.',
      language: 'en',
      createdAt: '2026-02-20T18:35:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-05',
      name: 'Michael Brooks',
      location: 'den-haag',
      rating: 5,
      message:
        'Business dinner that felt anything but formal — warm, relaxed, excellent wine list. Clients were impressed. Will definitely return.',
      language: 'en',
      createdAt: '2026-03-15T19:50:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-06',
      name: 'Laura Hughes',
      location: 'leiden',
      rating: 5,
      message:
        'Authentic flavours, no shortcuts. The branzino was grilled to perfection. One of the best Italian meals we have had in Holland.',
      language: 'en',
      createdAt: '2026-05-02T20:10:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-en-07',
      name: 'Robert Klein',
      location: 'den-haag',
      rating: 5,
      message:
        'From antipasto to cannoli, every course delighted us. You can taste the tradition. Highly recommend for anyone searching for real Italian cuisine.',
      language: 'en',
      createdAt: '2026-07-19T17:45:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-01',
      name: 'Giulia Romano',
      location: 'den-haag',
      rating: 5,
      message:
        'Finalmente un italiano vero all\'Aia! Pasta fatta con cura, ragù come a casa della nonna. Roberta e Giuseppe sono gentilissimi — ci siamo sentiti in famiglia.',
      language: 'it',
      createdAt: '2025-09-21T20:00:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-02',
      name: 'Marco Ferretti',
      location: 'leiden',
      rating: 5,
      message:
        'Serata perfetta a Leiden: ambiente intimo, vongole freschissime e un tiramisù che non ti dimentichi. Consigliatissimo a chi cerca cucina italiana autentica.',
      language: 'it',
      createdAt: '2025-12-16T19:30:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-03',
      name: 'Chiara Bianchi',
      location: 'den-haag',
      rating: 5,
      message:
        'Abbiamo pranzato il sabato: bruschette croccanti, risotto mantecato benissimo. Servizio attento senza essere invadente. Torneremo presto!',
      language: 'it',
      createdAt: '2026-02-01T12:45:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-04',
      name: 'Alessandro Conti',
      location: 'leiden',
      rating: 5,
      message:
        'Portato amici olandesi a cena: tutti entusiasti. Scaloppine e vino della casa impeccabili. Bacco Perbacco è un pezzo d\'Italia in Olanda.',
      language: 'it',
      createdAt: '2026-03-08T18:20:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-05',
      name: 'Francesca De Luca',
      location: 'den-haag',
      rating: 5,
      message:
        'Celebrazione di compleanno indimenticabile. Hanno curato ogni dettaglio, piatti generosi e sapori sinceri. Grazie di cuore!',
      language: 'it',
      createdAt: '2026-04-25T21:15:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-06',
      name: 'Luca Martini',
      location: 'leiden',
      rating: 5,
      message:
        'Qualità costante ogni volta che passiamo da Leiden. Antipasto misto da condividere e pasta al ragù da chef. Voto: 5 stelle piene.',
      language: 'it',
      createdAt: '2026-06-10T20:30:00.000Z',
      reply: null,
      repliedAt: null,
    },
    {
      id: 'fb-seed-it-07',
      name: 'Valentina Ricci',
      location: 'den-haag',
      rating: 5,
      message:
        'Roberta ci ha consigliato il piatto del giorno: una bella sorpresa. Ingredienti semplici, risultato eccellente. Il miglior ristorante italiano tra Den Haag e Leiden.',
      language: 'it',
      createdAt: '2026-08-01T19:00:00.000Z',
      reply: null,
      repliedAt: null,
    },
  ],
};
